title: iqbwl
author: iqbwl
email: iqbwlx@gmail.com
url: https://iqbwl.com
baseurl: ""
description: > # description of the site (multiple lines allowed)
  personal blogs

permalink: /:slug

favicon: "/assets/icons8-sauropod-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - no-style-please.md
  - no-style-please.gemspec
  - netlify.toml

include:
  - svg
  - img
  - migrated

# deployment
#host: 0.0.0.0
#port: 8000
